# .github/workflows/ci.yml

name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run lint
  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run end-to-end tests on desktop viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.STITCH_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.STITCH_USER_PASSWORD }}
        with:
          command: npm test
  cypress-tests-tablet:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run end-to-end tests on tablet viewport 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USER_EMAIL: ${{ secrets.STITCH_USER_EMAIL }}
          CYPRESS_USER_PASSWORD: ${{ secrets.STITCH_USER_PASSWORD }}
        with:
          command: npm run test:tablet
